In [1]:
%matplotlib nbagg

# DE(Differential Evolution)

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation

## 目的関数

In [6]:
def sphere_func(x: list):
    return sum([val ** 2 for val in x])

def rastrign_func(x: list):
    return sum([val ** 2 - 10 * np.cos(2 * np.pi * val) + 10 for val in x])

## DE method

In [54]:
def de(func, M: int=30, D: int=5, cr: float=0.9, fw: float=0.5,
       tmax: int=1000, fend: float=1e-5, xmin: int=-5, xmax: int=5):
    """
    @param M <int> : 粒子数
    @param D <int> : 解の次元数
    @param cr <float> : DEのパラメータ
    @param fw <float> : DEのパラメータ
    @param tmax <int> : 最大試行回数
    @param xmin <int> : 初期値の最小値
    @param xmax <int> : 初期値の最大値
    遺伝的アルゴリズムのうちの差分進化の実装
    """ 

    # 初期化処理
    # 位置
    x = (xmin - xmax) * np.random.rand(M, D) + xmax
    xnew = np.zeros((M, D))
    # 更新に利用するパラメータ
    v = np.zeros(D)
    u = np.zeros(D)
    # 解の評価値関数
    f = np.zeros(M)
    # 目的関数の値
    ftmp = 0
    xbest = np.zeros(D)
    fbest = float("inf")
    
    # 関数の初期値の終了
    for i in range(M):
        f[i] = func(x[i])
        fbest = f[i] if f[i] < fbest else fbest
    
    # 実行
    for t in range(tmax):
        for i in range(M):
            # iを除く3つの位置を取得
            randvec = np.random.randint(0, M, 3)
            while i in randvec:
                randvec = np.random.randint(0, M, 3)
            # 突然変異
            v = x[randvec[0]] + fw * (x[randvec[1]] - x[randvec[2]])
            # 交叉
            for j in range(D):
                rj = np.random.rand()
                u[j] = v[j] if rj <= cr else x[i][j]
            # 1つだけはvを採用することを保証
            j = np.random.randint(0, D)
            u[j] = v[j]
            # uの評価関数の計算
            ftmp = func(u)
            # uを採用するかどうかの判定
            if ftmp < f[i]:
                f[i] = ftmp
                x[i] = u
                fbest = ftmp
                xbest = x[i]
            else:
                xnew[i] = x[i]
        # xの更新
        x = xnew
        # 終了条件を満たしたとき
        if fbest < fend:
            break
        else:
            print(fbest)
            print(xbest)
            
    return fbest, xbest

In [55]:
de(sphere_func)

50.588404956350786
[ 6.29603154  1.34592365 -1.5078345  -2.13563809  1.51735506]
50.30064152392212
[-3.11685467  1.64636135  4.15938872  4.41298947  1.04898154]
2.433356144474894
[-0.58715279  0.29785575  1.10944778  0.82683543  0.29216175]
3.1062012755849566
[ 0.97733358  0.00309834  0.69810225 -0.82093411 -0.99485234]
8.601212736434094
[-0.13280469  0.52076547  2.04524606 -1.92428378 -0.65305394]
1.5759095214680785
[ 0.18450674 -0.83523307  0.67929959 -0.19592032 -0.5868729 ]
0.6907278652354412
[ 0.26086878 -0.13765141 -0.02363174 -0.72364456 -0.2819708 ]
2.9400453399263227
[-0.14884486 -0.17046912  0.89350898  0.23341454 -1.42688128]
0.6658203532421306
[-0.16280535  0.18275302 -0.69476231 -0.15915765 -0.31287423]
0.06921358020482964
[-0.16280535 -0.13750601 -0.09988807 -0.11536526 -0.02265675]
0.11320760034833295
[-0.20406942 -0.13765141  0.2094535   0.09233087  0.01481913]
0.1831988819138967
[-0.04101601  0.35395374 -0.05645779  0.20896871 -0.09683965]
0.11818977935215824
[-0.04212

(7.350438241685837e-06,
 array([ 6.30075386e-05, -1.71854396e-03, -7.60248961e-04,  1.16602083e-03,
         1.56700092e-03]))

In [53]:
de(rastrign_func)

74.0536688770109
[-3.04885439 -2.64697734 -0.57083113  0.24414784 -1.76439178]
36.665942778909155
[-0.73052885 -0.09010107  0.90177222  2.27102201 -0.15129458]
18.51446742883331
[-1.98607003  1.03784275  1.98047531  0.07783859 -1.84060641]
53.46640025600786
[-1.09648803  2.53604726 -0.89751826  3.91857359 -2.05686347]
43.51443625389387
[ 0.2937375   0.966764   -0.89751826  0.71045588  0.69637816]
43.23644448924123
[-3.04462909  1.32219495  0.06575904 -0.89107037 -1.74171805]
38.56254925876623
[0.05018891 0.59003556 0.06575904 2.81181589 1.94874823]
27.832308984694222
[ 0.16134308  0.13198711 -1.81705581 -0.84227129 -1.14890103]
30.456282195185764
[-1.94242687 -0.25243744  0.18753848 -0.98773036  1.82860359]
36.00498158389147
[-1.94230026  0.89242227  0.75682211 -1.68506432  0.93769462]
42.85410839288065
[-0.85547956  0.28586022 -0.53638805  1.93287802 -0.95433683]
14.993843141935553
[-1.08410462  0.13198711  0.98667681  1.11428885  0.15630082]
34.45884450183239
[-1.94230026 -0.05190852

(0.0, array([0., 0., 0., 0., 0.]))